### ISSUE TITLE
Golden chorus fruits delink when teleporting to unloaded chunks

### ISSUE THREAD

**Issue by Urias0** [freeeranger/choruswarps#4] opened 2021-03-11 02:04 UTC
Already the 3rd time that happened , i linked my enchanted golden chorus to the link in my house , i go 1000 bloc away , try to use it and it don't work and say "Not Linked" , it was 100% linked when i left my base

**Comment by freeeranger** [comment] 2021-03-11 06:52
Hmm, that seems odd. Just to clarify, when you specifically say  "enchanted chorus delink when too far", do you mean that it only happens with the enchanted version or just that you haven't tested with regular?

**Comment by Urias0** [comment] 2021-03-11 21:39
i didn't try with a normal one , i'm gonna try

**Comment by Urias0** [comment] 2021-03-11 21:47
Can confirm , normal fruit don't work too , i linked both again and go 1000 bloc away , not teleportation to my ender link , but when i'm near my base it work 
![image](https://user-images.githubusercontent.com/73038418/110859494-cc1ed500-82bb-11eb-96d0-6f127d97011a.png)

**Comment by Urias0** [comment] 2021-03-11 21:49
If u need to know my modlist or something specific just ask me , i'm will be glad to answer , this mod is pretty useful and balanced (well except this bug but it's just a bug)

**Comment by freeeranger** [comment] 2021-03-11 22:26
Thanks for the info. I don't think it's related to another mod tho, it's probably just me being an idiot :P. I'm gonna fix the issue this weekend, a lot of school n stuff rn. 

Which version of the mod are you using?

**Comment by Urias0** [comment] 2021-03-11 22:30
Ok nice 👍  , i'm using choruswarps-1.16.5-1.5c , thanks for answering that quickly btw

**Comment by freeeranger** [comment] 2021-03-11 22:39
And you're not traveling between dimensions right?

**Comment by Urias0** [comment] 2021-03-11 22:53
Nope , i was in the overworld and my base is in the overworld

**Comment by freeeranger** [comment] 2021-03-12 10:11
Hmmm, alright. So just to see if I've understood correctly, it works on close range but once you get further away it stops working right? If that's the case then I probably know what the issue is.

**Comment by Urias0** [comment] 2021-03-12 17:50
Yup that's it , seems like the fruit forgot the ender link  when the chunk is not loaded

**Comment by freeeranger** [comment] 2021-03-12 18:47
Yup, that's what I was thinking. In that case I simply just need to load the chunk so that shouldn't be too difficult. The reason I haven't encountered the issue is probably because I've only been testing in the spawn chunks :)

**Comment by Urias0** [comment] 2021-03-12 19:11
Ok nice seems like a good solution and ye that make sense in that case , have a good day dude :)

**Comment by freeeranger** [comment] 2021-03-13 17:49
So I just fixed the issue, the file is currently being uploaded to curseforge. Closing the issue, but feel free to let me know if you have any other issues and thanks for reporting!

**Closed as completed by freeeranger** 2021-03-13 17:49 UTC
Labels: bug, critical
