### ISSUE TITLE
Server-side warp issues and potential fix

### ISSUE THREAD

**Issue by tgarr0** [freeeranger/choruswarps#5] opened 2021-03-19 06:51 UTC
Mod version: 1.5c
Linking and warping fail on servers due to use of client-side-only position getters in a few places. I was able to make adjustments to this version's code to get everything working, and unintentionally also fixed the issue this version had with checking/retaining links to Ender Links in unloaded chunks. Hopefully it's still helpful with your more up-to-date code.
https://pastebin.com/EZrvunBj

**Comment by freeeranger** [comment] 2021-03-19 09:51
Damn, you're a true legend. I'll use your file and just implement my console experience compatibility fix  and then that version will be up to date with 1.6 and have all the fixes that you implemented. Thanks a lot! :)

**Comment by freeeranger** [comment] 2021-03-19 13:22
Everything seems to be working as intended now, thanks a lot! Closing this issue.

**Closed as completed by freeeranger** 2021-03-19 13:22 UTC
Labels: bug, critical
